sudo: false
dist: xenial

language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - "pip install -U pip setuptools"
  - "pip install -r requirements.txt"
  - "pip install -r dev/requirements-test.txt"
  - "pip install python-coveralls"

cache:
  directories:
    - $HOME/.pip-cache/

script:
  - "python setup.py test"

notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#icspy"
    use_notice: false
    skip_join: true
    template:
      - "build#%{build_number} (%{branch} - %{commit}): %{message}"

after_success:
  - "coveralls"
