name: Publish package ğŸ“¦

on:
  # Only to test if this PR works, should be removed before merging
  push:
    branches:
      - publish-pypi
  # Trigger on release created events
  release:
    types:
      - created

jobs:
  build-and-publish:
    name: Build and publish Python ğŸ distributions ğŸ“¦
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install build dependencies
      run: pip install tox poetry bump2version

    - name: Build the package
      run: poetry build

    - name: Poetry configuration âš™ï¸
      env:
        TEST_PYPI_API_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: |
        poetry config repositories.test_pypi https://test.pypi.org/legacy/
        poetry config pypi-token.test_pypi $TEST_PYPI_API_TOKEN

    - name: Publish ğŸ“¦ to Test PyPI ğŸ§ª
      env:
        PYPI_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
      run: |
        poetry publish -r test_pypi

    # - name: Publish ğŸ“¦ to PyPI ğŸ‰
    #   if: startsWith(github.ref, 'refs/tags')
    #   env:
    #     PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
    #   run: |
    #     poetry publish -r pypi
